### ISSUE TITLE
Split reaction_latex into two functions, one for LHS and one for RHS

### ISSUE THREAD

**Issue by arichar6** [USNavalResearchLaboratory/nepc#25]
https://github.com/USNavalResearchLaboratory/nepc/blob/9f789d262aa60094f08a586c7b5b146511d6633a/nepc/nepc.py#L941

Seems like there might be cases where it's useful to have just the LHS (or RHS) of the reaction latex. Seems like it should be simple enough to refactor this function into two separate functions. 

Thoughts?

**Comment by arichar6** [comment]
Or is this what the "lhsA_long" and "rhsA_long" metadata items are for?

**Comment by padamson** [comment]
lhsA_long is the latex form of one of the species on LHS. I like your idea of providing the full LHS and full RHS separately and together.  Maybe lhs_latex and rhs_latex then call the two functions to build reaction_latex.
