### ISSUE TITLE
I am not understanding what the specie metadata is

### ISSUE THREAD

**Issue by Swanekamp** [USNavalResearchLaboratory/nepc#56]
I am not sure what information the specie metadata is trying to convey. I think that this is likely not useful information and can be removed. If the specie metadata is kept, then at least it should be spelled correctly. Species is its own singular and plural.

**Comment by padamson** [comment]
The species metadata is meant to allow you to query all of the cross sections/rates by species. For example, you could ask for all of the cross sections for N or N2 or N2+. Another use case is you could query for all of the data by species and some other metadata, like all excitation cross sections for N. But, in thinking about it more, it would probably make sense to remove the species metadata from the cross section metadata and make it a column in the states table.
